apps/loginReg/urls.py
from django.conf.urls import url
from . import views
# ^ So we can call functions from our routes!
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
	url(r'^success$', views.success, name='success'),
	url(r'^logout$', views.logout, name='logout')
]

apps/tripPlan/urls.py
from django.conf.urls import url
from . import views
# ^ So we can call functions from our routes!
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'destination/(?P<id>\d+)', views.tripInfo, name='tripInfo'),
	url(r'add', views.addTrip, name='addTrip'),
	url(r'confirm', views.confirm, name='confirm'),
	url(r'join/(?P<id>\d+)', views.joinTrip, name='joinTrip')
]

travelBuddy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'travels/', include('apps.tripPlan.urls', namespace='tP')),
	url(r'^', include('apps.loginReg.urls', namespace='loginReg')),
]

apps/tripPlan/models.py
from __future__ import unicode_literals
from ..loginReg.models import User
from django.db import models

# Create your models here.
class travelPlan(models.Model):
	traveler = models.ManyToManyField(User, related_name='trip')
	destination = models.CharField(max_length=45)
	plan = models.CharField(max_length=200)
	start_date = models.DateField()
	end_date = models.DateField()
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

apps/tripPlan/forms.py
from django import forms
from .models import travelPlan
from django.contrib import messages
from datetime import date

class AddTrip(forms.ModelForm):
	# Since most of this form is assembled automatically using ModelForm tricks, these first two lines format the start and end date fields to use the date picker widget. ^_^

	start_date=forms.DateField(widget=forms.SelectDateWidget())
	end_date=forms.DateField(widget=forms.SelectDateWidget())
	# This section looks at the travelPlan model and makes fields for each of the stated values.
	class Meta:
		model = travelPlan
		fields = ['destination', 'plan', 'start_date', 'end_date']

	# This overrides (and includes) the ModelForm's clean function, which validates data, so that I can check to make sure all the dates are in the future, and that the start_date comes before the end_date
	def clean(self):
		# This runs the inheritied .clean()
		cleaned_data = super(AddTrip, self).clean()

		# Snags the start_date
		start = cleaned_data.get("start_date")
		# Snags the end_date
		end = cleaned_data.get("end_date")

		# Checks to see if the start comes after the end.
		print(start)
		print(end)
		print(date.today())
		print(start<date.today())
		if start < date.today():
			raise forms.ValidationError("Can't add an event that starts in the past!")
			messages.error(request, "Trip 'already began'. Not gonna let that happen, bub.")
			print('We just put up an error message...')
		if start < end:
			raise forms.ValidationError("The End Comes Before The Beginning!")
			messages.error(request, "Trip lasts negative days.")
			print('We just put up an error message...')
		# Now, when we run .clean() on registration forms, it will also check to make sure the start and end times make sense.
		return self.cleaned_data

apps/tripPlan/views.py
from django.shortcuts import render, redirect
from .models import travelPlan
from ..loginReg.models import User
from .forms import AddTrip
from django.contrib import messages
# Create your views here.
def index(request):
	context = {}
	context['user'] = User.objects.get(id=request.session['user_id'])
	context['upcomingTrips'] = travelPlan.objects.filter(traveler=context['user'])
	context['otherTrips'] = travelPlan.objects.exclude(traveler=context['user'])
	manyManager = travelPlan.objects.get(id=1)
	print('--------------------------------------')
	print(manyManager.traveler)
	print('--------------------------------------')
	return render(request, 'tripPlan/index.html', context)

def addTrip(request):
	# If you're not logged in...
	if not 'user_id' in request.session:
		# Then you shouldn't be here!  Move along!
		return redirect('loginReg:index')
	context = {}
	context['user'] = User.objects.get(id=request.session['user_id'])
	print(context['user'])
	context['addTrip'] = AddTrip()
	return render(request, 'tripPlan/add.html', context)

# Adds a new travelPlan to the database, and registers the logged in user to it.
def confirm(request):
	# Stores the form's data
	bound_form = AddTrip(request.POST)
	theTraveler = User.objects.get(id=request.session['user_id'])
	print(theTraveler)
	# Checks the data integrity using the guidelines in forms.py
	if bound_form.is_valid():
		# Saves the data to a new travelPlan object
		bound_form = bound_form.save()
		# We're done here.  Lets go back to the index.
		bound_form.traveler.add(theTraveler)
		bound_form.save()
		print('-------------------------')
		print(bound_form.traveler)
		print('-------------------------')
		print(bound_form.traveler)
		print("That shoulda worked.  Go check.")
		return redirect('tP:index')
	else:
		# Something has gone wrong!
		print("THIS TRIP IS RUINED!")
		# Go to .errors and look at all of the places that errors could get sorted to. (e.g. start_date, destination)
		print(bound_form.errors)
		for field in bound_form.errors:
			# If that section of the form has 1+ errors,
			if bound_form.errors[field]:
				# Report each error
				for error in bound_form.errors[field]:
					# By making an error flash message.
					messages.error(request, error)
		messages.error(request, 'Trip registration failed. Try again.')
		# Go back to addTrip to try again.
		return redirect('tP:addTrip')

def tripInfo(request, id):
	context = {}
	context['theTrip'] = travelPlan.objects.get(id=id)
	print (context['theTrip'].traveler)
	return render(request, 'tripPlan/tripInfo.html', context)

def joinTrip(request, id):
	theTraveler = User.objects.get(id=request.session['user_id'])
	theTrip = travelPlan.objects.get(id=id)
	theTrip.traveler.add(theTraveler)
	theTrip.save()
	return redirect('tP:index')

apps/tripPlan/templates/tripPlan/add.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Add Plan</title>
</head>
<body>
	<div id="header">
		<a href="{% url 'tP:index'%}">Home</a>  <a href="{% url 'loginReg:logout'%}">Logout</a>
	</div>
	{% if messages %}
		<ul class = 'messages'>
			{% for message in messages %}
				 <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		{% endif %}
		{% if AddTrip.non_field_errors %}
			{% for error in AddTrip.non_field_errors %}
				<li>{{error}}</li>
			{% endfor %}
		</ul>
	{% endif %}
	<h1>Add a Trip</h1>
	<form action="{% url 'tP:confirm' %}", method='POST'>
		{% csrf_token %}
		<input type="hidden" name="traveler" value={{user}}>
		{{addTrip.as_p}}
		<input type="submit" value="Add">
	</form>
</body>
</html>

apps/tripPlan/templates/tripPlan/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Travel Dashboard</title>
</head>
<body>
	<div id="header">
		<a href="{% url 'loginReg:logout'%}">Logout</a>
	</div>
	{% if messages %}
		<ul class = 'messages'>
			{% for message in messages %}
				 <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		{% endif %}
		{% if RegForm.non_field_errors %}
			{% for error in RegForm.non_field_errors %}
				<li>{{error}}</li>
			{% endfor %}
		</ul>
	{% endif %}
	<h1>Hello, {{user.first_name}}!</h1>
	<div>
		<h3>Your Trip Schedule</h3>
		<table>
			<thead>
				<th>Destination</th>
				<th>Departing</th>
				<th>Returning</th>
				<th>Plan</th>
			</thead>
			{% if upcomingTrips %}
			<tbody>
				{% for trip in upcomingTrips %}
				<tr>
					<td>
						<a href='{% url "tP:tripInfo" trip.id %}'>
							{{trip.destination}}
						</a>
					</td>
					<td>{{trip.start_date}}</td>
					<td>{{trip.end_date}}</td>
					<td>{{trip.plan}}</td>
				</tr>
				{% endfor %}
			</tbody>
			{% else %}
			<p>You have no upcoming trips! Did you use all your miles or something?</p>
			{% endif %}
		</table>
	</div>


	<div>
		<h3>Other User's Travel Plans</h3>
		<table>
			<thead>
				<th>Name</th>
				<th>Destination</th>
				<th>Departing</th>
				<th>Returning</th>
				<th>Do you want to join?</th>
			</thead>

			{% if otherTrips %}
			<tbody>
				{% for trip in otherTrips %}
				<tr>
					<td>
						{% for person in trip.traveler.all|slice:":1" %}
							{{person.first_name}} {{person.last_name}}
						{% endfor %}
					</td>
					<td>
						<a href='{% url "tP:tripInfo" trip.id %}'>
							{{trip.destination}}
						</a>
					</td>
					<td>{{trip.start_date}}</td>
					<td>{{trip.end_date}}</td>
					<td><a href="{% url 'tP:joinTrip' trip.id %}">Join</a></td>
				</tr>
				{% endfor %}
			</tbody>
			{% else %}
			<p>Nope.  Everyone else is boring.</p>
			{% endif %}
		</table>
	</div>
	<form action="{% url 'tP:addTrip' %}"><input type="submit" value="Add A New Trip"></form>
</body>
</html>

apps/tripPlan/templates/tripPlan/tripInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Destination</title>
</head>
<body>
	<div id="header">
		<a href="{% url 'tP:index'%}">Home</a>  <a href="{% url 'loginReg:logout'%}">Logout</a>
	</div>
	{% if messages %}
		<ul class = 'messages'>
			{% for message in messages %}
				 <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		{% endif %}
		{% if RegForm.non_field_errors %}
			{% for error in RegForm.non_field_errors %}
				<li>{{error}}</li>
			{% endfor %}
		</ul>
	{% endif %}
	<div id="travelInfo">
		<H1>{{theTrip.destination}}</H1>
		<p>Planned By:
			{% for person in theTrip.traveler.all|slice:":1" %}
				{{person.first_name}} {{person.last_name}}
			{% endfor %}
		</p>
		<p>Departs:  {{theTrip.start_date}}</p>
		<p>Returns:  {{theTrip.end_date}}</p>
		<p></p>
		<h2>Other users joining the trip:</h2>
		{% for person in theTrip.traveler.all|slice:"1:" %}
			<p>{{person.first_name}} {{person.last_name}}<p>
		{% endfor %}
	</div>
</body>
</html>